//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\ArithmeticGrammar.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class ArithmeticGrammarParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, CELL=14, NUMBER=15, COLTITLE=16, 
		WHITESPACE=17;
	public const int
		RULE_expression = 0, RULE_component = 1;
	public static readonly string[] ruleNames = {
		"expression", "component"
	};

	private static readonly string[] _LiteralNames = {
		null, "'min('", "','", "')'", "'max('", "'^'", "'%'", "'+'", "'-'", "'*'", 
		"'/'", "'+('", "'-('", "'('"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "CELL", "NUMBER", "COLTITLE", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ArithmeticGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static ArithmeticGrammarParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ArithmeticGrammarParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ArithmeticGrammarParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ComponentContext component() {
			return GetRuleContext<ComponentContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(ArithmeticGrammarParser.Eof, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 0, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 4; component(0);
			State = 5; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ComponentContext : ParserRuleContext {
		public ComponentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_component; } }
	 
		public ComponentContext() { }
		public virtual void CopyFrom(ComponentContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MinimumContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public MinimumContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterMinimum(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitMinimum(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinimum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AdditionContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public AdditionContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterAddition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitAddition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAddition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MultiplicationContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public MultiplicationContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterMultiplication(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitMultiplication(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplication(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ModuloContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public ModuloContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterModulo(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitModulo(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModulo(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryPlusParenthesisContext : ComponentContext {
		public ComponentContext component() {
			return GetRuleContext<ComponentContext>(0);
		}
		public UnaryPlusParenthesisContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterUnaryPlusParenthesis(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitUnaryPlusParenthesis(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryPlusParenthesis(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubstractionContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public SubstractionContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterSubstraction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitSubstraction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubstraction(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MaximumContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public MaximumContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterMaximum(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitMaximum(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMaximum(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenthesisContext : ComponentContext {
		public ComponentContext component() {
			return GetRuleContext<ComponentContext>(0);
		}
		public ParenthesisContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterParenthesis(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitParenthesis(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenthesis(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryPlusNumberContext : ComponentContext {
		public ITerminalNode NUMBER() { return GetToken(ArithmeticGrammarParser.NUMBER, 0); }
		public UnaryPlusNumberContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterUnaryPlusNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitUnaryPlusNumber(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryPlusNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberContext : ComponentContext {
		public ITerminalNode NUMBER() { return GetToken(ArithmeticGrammarParser.NUMBER, 0); }
		public NumberContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitNumber(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusParenthesisContext : ComponentContext {
		public ComponentContext component() {
			return GetRuleContext<ComponentContext>(0);
		}
		public UnaryMinusParenthesisContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterUnaryMinusParenthesis(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitUnaryMinusParenthesis(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusParenthesis(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DivisionContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public DivisionContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterDivision(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitDivision(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDivision(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CellContext : ComponentContext {
		public ITerminalNode CELL() { return GetToken(ArithmeticGrammarParser.CELL, 0); }
		public CellContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterCell(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitCell(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCell(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class UnaryMinusNumberContext : ComponentContext {
		public ITerminalNode NUMBER() { return GetToken(ArithmeticGrammarParser.NUMBER, 0); }
		public UnaryMinusNumberContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterUnaryMinusNumber(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitUnaryMinusNumber(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryMinusNumber(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowerContext : ComponentContext {
		public ComponentContext[] component() {
			return GetRuleContexts<ComponentContext>();
		}
		public ComponentContext component(int i) {
			return GetRuleContext<ComponentContext>(i);
		}
		public PowerContext(ComponentContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.EnterPower(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IArithmeticGrammarListener typedListener = listener as IArithmeticGrammarListener;
			if (typedListener != null) typedListener.ExitPower(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IArithmeticGrammarVisitor<TResult> typedVisitor = visitor as IArithmeticGrammarVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPower(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComponentContext component() {
		return component(0);
	}

	private ComponentContext component(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ComponentContext _localctx = new ComponentContext(Context, _parentState);
		ComponentContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_component, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				{
				_localctx = new MinimumContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 8; Match(T__0);
				{
				State = 9; component(0);
				State = 10; Match(T__1);
				}
				State = 17;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 12; component(0);
						State = 13; Match(T__1);
						}
						} 
					}
					State = 19;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
				}
				State = 20; component(0);
				State = 21; Match(T__2);
				}
				break;
			case T__3:
				{
				_localctx = new MaximumContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 23; Match(T__3);
				{
				State = 24; component(0);
				State = 25; Match(T__1);
				}
				State = 32;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 27; component(0);
						State = 28; Match(T__1);
						}
						} 
					}
					State = 34;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
				}
				State = 35; component(0);
				State = 36; Match(T__2);
				}
				break;
			case T__10:
				{
				_localctx = new UnaryPlusParenthesisContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 38; Match(T__10);
				State = 39; component(0);
				State = 40; Match(T__2);
				}
				break;
			case T__11:
				{
				_localctx = new UnaryMinusParenthesisContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 42; Match(T__11);
				State = 43; component(0);
				State = 44; Match(T__2);
				}
				break;
			case T__6:
				{
				_localctx = new UnaryPlusNumberContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 46; Match(T__6);
				State = 47; Match(NUMBER);
				}
				break;
			case T__7:
				{
				_localctx = new UnaryMinusNumberContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 48; Match(T__7);
				State = 49; Match(NUMBER);
				}
				break;
			case T__12:
				{
				_localctx = new ParenthesisContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 50; Match(T__12);
				State = 51; component(0);
				State = 52; Match(T__2);
				}
				break;
			case NUMBER:
				{
				_localctx = new NumberContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 54; Match(NUMBER);
				}
				break;
			case CELL:
				{
				_localctx = new CellContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 55; Match(CELL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 78;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 76;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
					case 1:
						{
						_localctx = new PowerContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 58;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 59; Match(T__4);
						State = 60; component(14);
						}
						break;
					case 2:
						{
						_localctx = new ModuloContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 61;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 62; Match(T__5);
						State = 63; component(13);
						}
						break;
					case 3:
						{
						_localctx = new AdditionContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 64;
						if (!(Precpred(Context, 11))) throw new FailedPredicateException(this, "Precpred(Context, 11)");
						State = 65; Match(T__6);
						State = 66; component(12);
						}
						break;
					case 4:
						{
						_localctx = new SubstractionContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 67;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 68; Match(T__7);
						State = 69; component(11);
						}
						break;
					case 5:
						{
						_localctx = new MultiplicationContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 70;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 71; Match(T__8);
						State = 72; component(10);
						}
						break;
					case 6:
						{
						_localctx = new DivisionContext(new ComponentContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_component);
						State = 73;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 74; Match(T__9);
						State = 75; component(9);
						}
						break;
					}
					} 
				}
				State = 80;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return component_sempred((ComponentContext)_localctx, predIndex);
		}
		return true;
	}
	private bool component_sempred(ComponentContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 13);
		case 1: return Precpred(Context, 12);
		case 2: return Precpred(Context, 11);
		case 3: return Precpred(Context, 10);
		case 4: return Precpred(Context, 9);
		case 5: return Precpred(Context, 8);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', 'T', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\a', '\x3', '\x12', '\n', '\x3', '\f', '\x3', '\xE', 
		'\x3', '\x15', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\a', '\x3', '!', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', '$', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', ';', '\n', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 'O', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', 'R', '\v', '\x3', '\x3', '\x3', '\x2', '\x3', 
		'\x4', '\x4', '\x2', '\x4', '\x2', '\x2', '\x2', '\x61', '\x2', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x4', ':', '\x3', '\x2', '\x2', '\x2', '\x6', 
		'\a', '\x5', '\x4', '\x3', '\x2', '\a', '\b', '\a', '\x2', '\x2', '\x3', 
		'\b', '\x3', '\x3', '\x2', '\x2', '\x2', '\t', '\n', '\b', '\x3', '\x1', 
		'\x2', '\n', '\v', '\a', '\x3', '\x2', '\x2', '\v', '\f', '\x5', '\x4', 
		'\x3', '\x2', '\f', '\r', '\a', '\x4', '\x2', '\x2', '\r', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\xE', '\xF', '\x5', '\x4', '\x3', '\x2', '\xF', 
		'\x10', '\a', '\x4', '\x2', '\x2', '\x10', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x11', '\xE', '\x3', '\x2', '\x2', '\x2', '\x12', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x14', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x13', '\x3', '\x2', '\x2', '\x2', '\x16', '\x17', '\x5', 
		'\x4', '\x3', '\x2', '\x17', '\x18', '\a', '\x5', '\x2', '\x2', '\x18', 
		';', '\x3', '\x2', '\x2', '\x2', '\x19', '\x1A', '\a', '\x6', '\x2', '\x2', 
		'\x1A', '\x1B', '\x5', '\x4', '\x3', '\x2', '\x1B', '\x1C', '\a', '\x4', 
		'\x2', '\x2', '\x1C', '\"', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1E', 
		'\x5', '\x4', '\x3', '\x2', '\x1E', '\x1F', '\a', '\x4', '\x2', '\x2', 
		'\x1F', '!', '\x3', '\x2', '\x2', '\x2', ' ', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '!', '$', '\x3', '\x2', '\x2', '\x2', '\"', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\"', '#', '\x3', '\x2', '\x2', '\x2', '#', '%', '\x3', 
		'\x2', '\x2', '\x2', '$', '\"', '\x3', '\x2', '\x2', '\x2', '%', '&', 
		'\x5', '\x4', '\x3', '\x2', '&', '\'', '\a', '\x5', '\x2', '\x2', '\'', 
		';', '\x3', '\x2', '\x2', '\x2', '(', ')', '\a', '\r', '\x2', '\x2', ')', 
		'*', '\x5', '\x4', '\x3', '\x2', '*', '+', '\a', '\x5', '\x2', '\x2', 
		'+', ';', '\x3', '\x2', '\x2', '\x2', ',', '-', '\a', '\xE', '\x2', '\x2', 
		'-', '.', '\x5', '\x4', '\x3', '\x2', '.', '/', '\a', '\x5', '\x2', '\x2', 
		'/', ';', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', '\t', '\x2', 
		'\x2', '\x31', ';', '\a', '\x11', '\x2', '\x2', '\x32', '\x33', '\a', 
		'\n', '\x2', '\x2', '\x33', ';', '\a', '\x11', '\x2', '\x2', '\x34', '\x35', 
		'\a', '\xF', '\x2', '\x2', '\x35', '\x36', '\x5', '\x4', '\x3', '\x2', 
		'\x36', '\x37', '\a', '\x5', '\x2', '\x2', '\x37', ';', '\x3', '\x2', 
		'\x2', '\x2', '\x38', ';', '\a', '\x11', '\x2', '\x2', '\x39', ';', '\a', 
		'\x10', '\x2', '\x2', ':', '\t', '\x3', '\x2', '\x2', '\x2', ':', '\x19', 
		'\x3', '\x2', '\x2', '\x2', ':', '(', '\x3', '\x2', '\x2', '\x2', ':', 
		',', '\x3', '\x2', '\x2', '\x2', ':', '\x30', '\x3', '\x2', '\x2', '\x2', 
		':', '\x32', '\x3', '\x2', '\x2', '\x2', ':', '\x34', '\x3', '\x2', '\x2', 
		'\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ':', '\x39', '\x3', '\x2', 
		'\x2', '\x2', ';', 'P', '\x3', '\x2', '\x2', '\x2', '<', '=', '\f', '\xF', 
		'\x2', '\x2', '=', '>', '\a', '\a', '\x2', '\x2', '>', 'O', '\x5', '\x4', 
		'\x3', '\x10', '?', '@', '\f', '\xE', '\x2', '\x2', '@', '\x41', '\a', 
		'\b', '\x2', '\x2', '\x41', 'O', '\x5', '\x4', '\x3', '\xF', '\x42', '\x43', 
		'\f', '\r', '\x2', '\x2', '\x43', '\x44', '\a', '\t', '\x2', '\x2', '\x44', 
		'O', '\x5', '\x4', '\x3', '\xE', '\x45', '\x46', '\f', '\f', '\x2', '\x2', 
		'\x46', 'G', '\a', '\n', '\x2', '\x2', 'G', 'O', '\x5', '\x4', '\x3', 
		'\r', 'H', 'I', '\f', '\v', '\x2', '\x2', 'I', 'J', '\a', '\v', '\x2', 
		'\x2', 'J', 'O', '\x5', '\x4', '\x3', '\f', 'K', 'L', '\f', '\n', '\x2', 
		'\x2', 'L', 'M', '\a', '\f', '\x2', '\x2', 'M', 'O', '\x5', '\x4', '\x3', 
		'\v', 'N', '<', '\x3', '\x2', '\x2', '\x2', 'N', '?', '\x3', '\x2', '\x2', 
		'\x2', 'N', '\x42', '\x3', '\x2', '\x2', '\x2', 'N', '\x45', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'H', '\x3', '\x2', '\x2', '\x2', 'N', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'R', '\x3', '\x2', '\x2', '\x2', 'P', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 'Q', '\x5', '\x3', 
		'\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', '\x2', '\a', '\x13', 
		'\"', ':', 'N', 'P',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
